In [20]:
import torch
from torch.nn import Linear, ReLU, Sigmoid, Softmax, Sequential, MSELoss, BCELoss, CrossEntropyLoss

# Линейные слои & Ф.Активации

In [4]:
X = torch.randn(4,2)
W = torch.randn(2,3)
layer = Linear(2,3)

print(X, W, X @ W, layer.weight, layer(X), sep='\n')

tensor([[-0.1569,  0.4879],
        [-0.7986,  0.6605],
        [-1.8552,  0.5687],
        [ 0.4638,  1.0925]])
tensor([[-0.5361, -0.1343,  0.7091],
        [-0.4250, -0.9717, -0.5993]])
tensor([[-0.1232, -0.4530, -0.4036],
        [ 0.1475, -0.5346, -0.9622],
        [ 0.7529, -0.3035, -1.6564],
        [-0.7129, -1.1239, -0.3258]])
Parameter containing:
tensor([[-0.5327,  0.0139],
        [-0.3103,  0.6112],
        [-0.1701,  0.1980]], requires_grad=True)
tensor([[-0.3264, -0.0693, -0.0701],
        [ 0.0179,  0.2353,  0.0732],
        [ 0.5795,  0.5071,  0.2347],
        [-0.6486,  0.1076, -0.0560]], grad_fn=<AddmmBackward0>)


In [5]:
X = torch.randn(3,3)
layer = ReLU()
layer(X)

tensor([[0.6663, 0.0000, 0.0000],
        [1.7150, 0.0000, 0.0000],
        [0.0000, 1.3142, 1.1931]])

In [6]:
X1 = torch.randn(3, 1)
layer = Sigmoid()
layer(X1), X1

(tensor([[0.3507],
         [0.4716],
         [0.5296]]),
 tensor([[-0.6159],
         [-0.1137],
         [ 0.1186]]))

In [7]:
layer = Softmax()
layer(X), X

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


(tensor([[0.6337, 0.0754, 0.2909],
         [0.8756, 0.0331, 0.0913],
         [0.0869, 0.4842, 0.4289]]),
 tensor([[ 0.6663, -1.4628, -0.1123],
         [ 1.7150, -1.5601, -0.5463],
         [-0.4036,  1.3142,  1.1931]]))

In [8]:
model = Sequential(
    Linear(3, 10),
    ReLU(),
    Linear(10, 20),
    ReLU(),
    Linear(20, 1),
)
print(model(X))

tensor([[0.2689],
        [0.2980],
        [0.1061]], grad_fn=<AddmmBackward0>)


# Ф.Потерь


In [9]:
loss_fn = MSELoss()
y = torch.tensor([[0.5],[1.5],[0.7]])
y_hat = torch.tensor([[0.6],[0.2],[0.5]])
print(loss_fn(y_hat, y))

tensor(0.5800)


In [10]:
loss_fn = BCELoss()
y = torch.tensor([[1],[1.],[0.]])
y_hat = torch.tensor([[0.9],[0.3],[0.2]])
print(loss_fn(y_hat, y))

tensor(0.5108)


In [11]:
loss_fn = CrossEntropyLoss()
y = torch.tensor([1, 2, 0])
y_hat = torch.randn(3,3).abs()
print(loss_fn(y_hat, y))
y_hat

tensor(0.8355)


tensor([[0.5839, 0.5406, 0.5191],
        [0.5009, 1.2433, 2.5754],
        [0.7973, 0.2457, 1.0920]])

# Метрики

In [12]:
y = torch.tensor([[0.5],[1.5],[0.7]])
y_hat = torch.tensor([[0.6],[0.2],[0.5]])

score = (y-y_hat).abs() / y * 100
score.mean()

tensor(45.0794)

In [13]:
y = torch.tensor([[1.],[1.],[0.]])
y_hat = torch.tensor([[0.9],[0.3],[0.2]])

score = (y_hat.round() == y).sum() / len(y) * 100
score

tensor(66.6667)

In [14]:
y = torch.tensor([1, 2, 0])
y_hat = torch.tensor([
    [-1.2, 2.2, 0.2],
    [2.3, 0.2, 0.7],
    [0.9, -2.2, -1.2]
])

score = (y_hat.argmax(1) == y).sum() / len(y) * 100
score

tensor(66.6667)

# Обучение нейросети

In [15]:
X = torch.load('data.pt')
Y = torch.load('target.pt')
X[:3], Y[:3], len(X)

(tensor([[7.4000, 2.8000, 6.1000, 1.9000],
         [6.7000, 3.1000, 5.6000, 2.4000],
         [6.0000, 3.4000, 4.5000, 1.6000]]),
 tensor([2, 2, 1]),
 150)

In [16]:
X_train, X_value = X[:100], X[100:]
Y_train, Y_value = Y[:100], Y[100:]

model = Sequential(Linear(4, 16),
                   ReLU(),
                   Linear(16, 3))

loss_fn = CrossEntropyLoss()

In [17]:
from torch.optim import SGD

optimizer = SGD(model.parameters(), lr=0.02)

In [18]:
for _ in range(1000):
  loss = loss_fn(model(X_train), Y_train)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  print(f'{loss:.3f}')

1.388
1.092
0.994
0.961
0.948
0.940
0.933
0.927
0.922
0.916
0.911
0.906
0.900
0.895
0.890
0.885
0.880
0.875
0.869
0.864
0.859
0.854
0.849
0.844
0.839
0.834
0.829
0.824
0.819
0.814
0.809
0.804
0.799
0.794
0.789
0.784
0.779
0.774
0.769
0.765
0.760
0.755
0.750
0.745
0.741
0.736
0.731
0.727
0.722
0.718
0.713
0.709
0.704
0.700
0.696
0.691
0.687
0.683
0.679
0.675
0.671
0.666
0.662
0.659
0.655
0.651
0.647
0.643
0.639
0.636
0.632
0.628
0.625
0.621
0.618
0.615
0.611
0.608
0.605
0.601
0.598
0.595
0.592
0.589
0.586
0.583
0.580
0.577
0.574
0.571
0.568
0.566
0.563
0.560
0.558
0.555
0.552
0.550
0.547
0.545
0.542
0.540
0.538
0.535
0.533
0.531
0.528
0.526
0.524
0.522
0.520
0.517
0.515
0.513
0.511
0.509
0.507
0.505
0.503
0.501
0.499
0.497
0.496
0.494
0.492
0.490
0.488
0.487
0.485
0.483
0.481
0.480
0.478
0.476
0.475
0.473
0.471
0.470
0.468
0.467
0.465
0.463
0.462
0.460
0.459
0.457
0.456
0.454
0.453
0.452
0.450
0.449
0.447
0.446
0.445
0.443
0.442
0.440
0.439
0.438
0.436
0.435
0.434
0.433
0.431
0.430
0.42

In [19]:
score = (model(X_value).argmax(1) == Y_value).sum() / len(Y_value) * 100
f'точность модели: {score:.0f}%'

'точность модели: 96%'